# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gilt < Formula
  desc "A GIT layering tool"
  homepage "https://github.com/retr0h/gilt"
  version "2.2.1"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    url "https://github.com/retr0h/gilt/releases/download/v2.2.1/gilt_2.2.1_darwin_all"
    sha256 "c6be7215dfac562e1b9e83747b944a421c2b03f98b1da54f4dbe0aecef123798"

    def install
      bin.install "gilt_2.2.1_darwin_all" => "gilt"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/retr0h/gilt/releases/download/v2.2.1/gilt_2.2.1_linux_amd64"
      sha256 "3051b49525a11a140c747de629787f4e02f2ad772c792ad287192ed37edb3e43"

      def install
        bin.install "gilt_2.2.1_linux_amd64" => "gilt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/retr0h/gilt/releases/download/v2.2.1/gilt_2.2.1_linux_arm64"
      sha256 "d8231b36a83f373757e53bb291a26999a17d52d1fe74e3edf75f10a776e61de6"

      def install
        bin.install "gilt_2.2.1_linux_arm64" => "gilt"
      end
    end
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
