# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGilt < Formula
  desc "A GIT layering tool"
  homepage "https://github.com/retr0h/go-gilt"
  version "2.0"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/retr0h/go-gilt/releases/download/v2.0/go-gilt_2.0_darwin_amd64"
      sha256 "380952e91114b59b98451fe8b8e0bf97dba5740679705ab394f91019ce6f7118"

      def install
        bin.install "go-gilt_2.0_darwin_amd64" => "go-gilt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/retr0h/go-gilt/releases/download/v2.0/go-gilt_2.0_darwin_arm64"
      sha256 "5ef4ddabadad59ce4c234e75d76f4d07efc427579faeed16f8a17a2aaabbdb06"

      def install
        bin.install "go-gilt_2.0_darwin_arm64" => "go-gilt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/retr0h/go-gilt/releases/download/v2.0/go-gilt_2.0_linux_arm64"
      sha256 "a246a61e50b7ba7dcbd6756c227112e3521a63c3e858b74c8004015c9971d64f"

      def install
        bin.install "go-gilt_2.0_linux_arm64" => "go-gilt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/retr0h/go-gilt/releases/download/v2.0/go-gilt_2.0_linux_amd64"
      sha256 "490721232ba16a227a6913618ba7b7865ca647ce770f1b343004c1b436804955"

      def install
        bin.install "go-gilt_2.0_linux_amd64" => "go-gilt"
      end
    end
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
